### ISSUE TITLE
Add documentation for how calculate_diversities() works

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/hagis#19]
> The `calculate_diversities()` function does not describe how the diversities
   are calculated. Please add documentation describing how they are calculated.

**Comment by adamhsparks** [comment]
I've added documentation to both the help file and vignette for how `calculate_diversities()` works. @AGmccoy, can you double check my work, please? 

Just checking the vignette would be sufficient, I can then make any necessary changes in the Roxygen code for the help file based on your comments or corrections in the vignette file.

https://github.com/openplantpathology/hagis/blob/47e8478b1fe331d6cf7134812002415ed579e13b/vignettes/hagis.Rmd#L172

thanks!

**Comment by AGmccoy** [comment]
I agree with your documentation of the diversity indices. Succinct but explains what to expect/how to interpret the output!

Thanks Adam!
