### ISSUE TITLE
Document the data sets

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/hagis#20]
>  Please document the data sets available and what the variables mean.

**Comment by adamhsparks** [comment]
Austin, can you help me with this? I'm fairly sure I could do it, but it is your data so I don't want to stuff something up. I'll set up the skeleton file and let you fill in details unless you would like to handle it all yourself?

**Comment by adamhsparks** [comment]
@AGmccoy, I've moved the data into the "/data" directory and added the skeleton file to document the data. Can you complete the documentation of the dataset in the documentation file, see https://github.com/openplantpathology/hagis/blob/devel/R/data.R?

Lines 14-20 need descriptors

Line 25 needs a source or if it comes from published data, change `@source` to `@reference` and provide a reference.

**Comment by AGmccoy** [comment]
Gotcha, will do. Thanks Adam!

Austun

**Comment by AGmccoy** [comment]
@adamhsparks i think I did the @source description correctly, but before i close this you may want to check. My Phytophthora sojae pathotype study isn't published yet, so I kept it @source and added a small description. I may have mis-understood what i was supposed to do there...

**Comment by adamhsparks** [comment]
I made a few minor edits to it but looks to me like you understood perfectly! Thanks, @AGmccoy.
