### ISSUE TITLE
Reorder columns in summarize_gene()

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/hagis#23]
> summarize_gene function produces a data frame with three columns, I suggest replacing second column name to “No: of virulent isolates” and make it first column e.g.
No: virulent isolates      gene         percent_pathogenic

**Comment by adamhsparks** [comment]
I've replaced `N_susc` with `N_virulent_isolates` within function and documentation, which makes a much longer colname but maybe more descriptive.

I don't like reordering the columns though. To me the gene should still be first. A user can reorder the columns or rearrange the sort order in the rows if they like. This could be added to the vignette as an example?

Thoughts, @noelzach and @AGmccoy?

**Comment by AGmccoy** [comment]
I am also not a fan of reordering the columns. with how we have it now it should be easy to interpret by reading the column headers from left to right (On X gene there are 15 virulent isolates which make up this percent of the total population tested). I think this was the point the reviewer was trying to make, but I think how it is now is just as intuitive.

I do think your renaming of the column, while long, will make it easier to understand for the end user.

**Comment by adamhsparks** [comment]
Yeah, I thought the colnames were a bit long as requested but I guess tab completion and/or indexing will help with that.
