### ISSUE TITLE
Themes in plots

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/hagis#3]
For comment and discussion. The plotting is an integral feature of this package. However, I'd like to raise the suggestion of just returning a non-themed _ggplot2_ object such that users can theme them themselves using any number of built-in _ggplot2_ themes or third-party themes (I have [one just for USQ colours and typography](https://adamhsparks.github.io/theme.usq/) that I'd use).

No reason you couldn't wrap the theme up and deploy it with this package for continued use, but I'd prefer a default object be returned with the user deciding the theme.

**Comment by noelzach** [comment]
Yes, I think that is a good suggestion. The user should be able to manipulate the plot theme as they see fit. We can keep our themes deployed with the package if users want to use them. We found them helpful for presentations.
