### ISSUE TITLE
Does susceptibilities() need to be renamed?

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/hagis#4]
Currently `susceptibilities()` summarises the _Rps_ gene summaries and returns that. A better name might be `rps_summary()`?

**Comment by adamhsparks** [comment]
@zachary-foster, thoughts?

**Comment by adamhsparks** [comment]
`summarise_Rps()` might be a good one and `visualise_Rps()` for the graphing?

**Comment by adamhsparks** [comment]
I've renamed these functions as I suggested. If there are objections or further suggestions, I'm willing to entertain them. Closing for now. Please reopen if necessary.

**Comment by zachary-foster** [comment]
Hi @adamhsparks, did you mean to ping me or Zachary Noel? Either way, I think the new names are better.

**Comment by noelzach** [comment]
Oh didn't catch this. Seems like you already closed it. Yes, I agree, the new names seem better.

**Comment by adamhsparks** [comment]
Hah, oops, wrong Zach. Sorry, mate! It autofilled and I didn't pay attention. 

Should have pinged @AGmccoy too.

**Comment by AGmccoy** [comment]
just seeing this. yes, new name is better. Definately describes what they will be getting out of the function.

Thanks Adam!

**Comment by AGmccoy** [comment]
I like summarize_rps()

**Comment by adamhsparks** [comment]
@AGmccoy, done!
