### ISSUE TITLE
Need some help with some values in the script

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/hagis#5]
@AGmccoy, you have `sample` and `gene` referenced on lines [74 -76](https://github.com/AGmccoy/Phytopthora-sojae-Pathotype-analysis/blob/a7562af98878e25108c697f1c6b504de3ec40686/functions_themes.R#L74). However, I can't find these values in the script or the Rmd. I'm guessing `gene` is `Rps`?

What is the corresponding field for `sample`?

**Comment by AGmccoy** [comment]
Yes, sample corresponds to isolate and gene is for Rps.

Ausyin

**Comment by adamhsparks** [comment]
thanks, mate!
